MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://VGGImageNetPretrained/JCJOHNS/VGG-16" 
  BACKBONE:
    CONV_BODY: "VGG16-OICR"
  WSOD_ON: True
  FASTER_RCNN: False
  ROI_HEADS:
    SCORE_THRESH: 0.001
    NMS: 0.3
    BG_IOU_THRESHOLD: 0.3
  ROI_BOX_HEAD:
    NUM_CLASSES: 21
    POOLER_METHOD: "ROIPool"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.125,)
    FEATURE_EXTRACTOR: "VGG16.roi_head"
  ROI_WEAK_HEAD:
    PREDICTOR: "MISTPredictor"
    LOSS: "RoIRegLoss"
    OICR_P: 0.15
    REGRESS_ON: True
    ACTIVE_LOSS: "RoIRegActiveLoss"
    ACTIVE_LOSS_WEIGHT: 1.0
DB:
  METHOD:  'none' #'concrete' or 'none'
DATASETS:
  TRAIN: ("voc_2007_train", "voc_2007_val", )
  TEST: ("voc_2007_test",)
PROPOSAL_FILES:
  TRAIN: ('proposal/SS-voc_2007_train-boxes.pkl', 'proposal/SS-voc_2007_val-boxes.pkl', )
  TEST:  ('proposal/SS-voc_2007_test-boxes.pkl',)
DATALOADER:
  SIZE_DIVISIBILITY: 32
INPUT:
  MIN_SIZE_TRAIN: (480, 576, 688, 864, 1000, 1200) 
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 2000
SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  WARMUP_ITERS: 200
  STEPS: (20000, 26700)
  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 2000
SOLVER_CDB:
  BASE_LR: 0.0001
  GAMMA: 3.0
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 26700)
TEST:
  IMS_PER_BATCH: 1
  BBOX_AUG:
    ENABLED: True
    HEUR: "AVG"
    H_FLIP: True
    SCALES: (480, 576, 688, 864, 1000, 1200) 
    MAX_SIZE: 2000
    SCALE_H_FLIP: True
SEED: 1234
ACTIVE:
  INPUT_FILE: None
  PSEUDO_BOXES_FILE: None
  LOSS:
    STRONG_LOSS_ON_MIL: False
  IMG_STRONG_DET_WEIGHT: 0.0
  WEIGHTS_BBX_LOSS: 1.0
  WEIGHTED_SAMPLING: True
